version: 2.1

jobs:
  echo_run_a:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: ECHO
          command: "echo A"

  echo_run_b:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: ECHO
          command: "echo B"
  
  echo_run_c:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: ECHO
          command: "echo C"

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello

  release:
    jobs:
      - echo_run_a:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /([0-9]+).([0-9]+).([0-9]+)-([0-9]+)/
      - echo_run_b:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /([0-9]+).([0-9]+).([0-9]+)-([0-9]+)/
          requires:
            - echo_run_a
      - echo_run_c:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /([0-9]+).([0-9]+).([0-9]+)-([0-9]+)/
          requires:
            - echo_run_b

