
name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release:')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}
      - name: Create & Push Tag
        run: |
          git tag $(cat .app-version)
          git push origin $(cat .app-version)
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
