    
name: Manage Milestone for Release

on:
  push:
    tags:
      - '*'

jobs:
  manage-milestone-for-release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release:')
    steps:
      - uses: actions/checkout@v3
      - name: Set Milestone to Close
        run: |
          CURRENT_VERSION=$(cat .app-version)
          BUILD_NAME=`echo $CURRENT_VERSION | sed -e 's/\([0-9\.]*\)-\(.*\)/\1/g'`
          echo "CLOSE_MILESTONE=${BUILD_NAME}" >> $GITHUB_ENV
      - name: Close Current Milestone
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          milestone-title: ${{ env.CLOSE_MILESTONE }}
      - name: Set Milestone to Create
        run: |
          CURRENT_VERSION=$(cat .app-version)
          VERSION_MAJOR=`echo $CURRENT_VERSION | cut -d. -f1`
          VERSION_MINOR=`echo $CURRENT_VERSION | cut -d. -f2`
          MILESTONE="$VERSION_MAJOR.$((VERSION_MINOR + 2)).0"
          echo "CREATE_MILESTONE=${MILESTONE}" >> $GITHUB_ENV
      - name: Create New Milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ env.CREATE_MILESTONE }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
