name: Publish Releases

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      name: Publish GitHub Release
      with:
        generateReleaseNotes: true
        token: ${{ secrets.BOT_PAT }}
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_PAT }}